### ISSUE TITLE
Bot favours events over APIs when searching docs

### ISSUE THREAD

**Issue by Lupus590** [SquidDev-CC/FAQBot-CC#25]
Searching for `peripheral.find` returns the `peripheral` event, not the API page.

![image](https://user-images.githubusercontent.com/9790321/106892726-6354a380-66e4-11eb-8fbd-e13a9df150a6.png)

**Comment by Lupus590** [comment]
Arguably `peripheral` should be giving two results, the APi and the event.

**Comment by SquidDev** [comment]
Fixed in SquidDev/illuaminate@6352dc61f712732c211e3191a16030f993303565

> if someone wants to work on that.

I guess my cunning plan to get someone else to do the work didn't pan out :/.
