### ISSUE TITLE
make everything a / command

### ISSUE THREAD

**Issue by CitizenFoffie** [SquidDev-CC/FAQBot-CC#32]
things like /eval

**Comment by Wojbie** [comment]
Problem with that idea is that / commands disable ability to write newline. It would make writing multi line code to execute a bit annoying. One would have to write out all the code and then go back to beginning of message to add `/eval`.

**Comment by SquidDev** [comment]
As Wojbie said, there's really not any benefit to converting eval - it ends up being incredibly clunky to use. I also believe that you can't use slash commands in replies

**Comment by CitizenFoffie** [comment]
I was just using eval as a example, maybe not everything then.

**Comment by SquidDev** [comment]
The only other non-slash commands are `%help` and `%about`. I guess you could put them under a `/cc` sub-command, I guess it just doesn't feel worth it?
