### ISSUE TITLE
Monitor Rendering FAQ more details

### ISSUE THREAD

**Issue by 1Turtle** [SquidDev-CC/FAQBot-CC#48]
The faq related to monitor rendering issues is kept very briefly.
It also is pretty old.

A current issue many players have are darker monitor screens within Oculus or Iris and having no shader active _(or similar behaviour)_

I feel like the faq should get a revisit to address those issues more directly, as well as some other rendering bugs like the monitor screen being completelty invisible within shaders.

Thoughts about this?

**Comment by SquidDev** [comment]
Iris bug is now fixed - https://github.com/IrisShaders/Iris/issues/2053.
