### ISSUE TITLE
[Suggestion] Quality-of-life improvements

### ISSUE THREAD

**Issue by znepb** [SquidDev-CC/FAQBot-CC#50]
Message decay & allow users with Manage Messages to use the delete button. I don't really want my channels to be flooded with eval results, so it would be nice if I could do something like `/decay 30s` to make them decay after 30 seconds or something like that. Also, it would be cool if users with the Manage Messages permission could always use the Delete button, just as a quick shortcut instead of having to mess around with right click menus.

**Comment by SquidDev** [comment]
Have added support for deleting via the button in the above commit. I'm afraid I'm not going to add `/decay` support - it's a lot of code (and state) to maintain for a relatively niche feature.
