### ISSUE TITLE
[bug] `%exec` is no longer working for the CC:Aide bot

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/FAQBot-CC#56]
Any attempts to `%exec` anything will currently fail.

> :bangbang: Unknown error when running code

Other commands like faq/docs/source still seem to work.

**Comment by fatboychummy** [comment]
Oh hold on, was testing file operations but it seems the bot is entirely down -- all requests return said error running code.

**Comment by SquidDev** [comment]
Thanks for the heads up, have restarted it.
